### ISSUE TITLE
Not all SNPs in output

### ISSUE THREAD

**Issue by grantfinch** [calbers191/23andme2vcf-py#1]
Hi Chris,

It seems that a number of SNPs are not making it into the VCF. An example is below:

23 and me file:
rs11260542	1	1110019	AG
VCF:
chr1	1110019	rs11260542	A	G	.	.	.	GT	0/1

But when the 23 and me file says:
rs11260542	1	1110019	AA
The entire SNP is absent from the output VCF.

Thanks,
-Grant

**Comment by calbers191** [comment]
Grant-

This is the expected behavior. This tool is designed to include only SNPs that differ from the reference sequence. Any SNP that is missing from the VCF is either a homozygous match for the reference or was excluded as an insertion, deletion, or no call.

Is this something you'd want to see? I can generate additional files that contain info about missing calls or change the output to something like a "gVCF", which would include all sites regardless of whether there is a variant at that position.

Thanks,
Chris

**Comment by grantfinch** [comment]
Hi Chris,

Thanks for that explanation. I suspected that was the reason for the non-inclusion in the output, but wasn't sure.

I think that a gVCF might be useful as a secondary output to allow for comparisons between multiple people.

Thanks,
Grant

**Comment by calbers191** [comment]
Grant-

There's now a -gvcf option, which will print a line for every SNP. Check the README for details on implementation.

Let me know if you have any other suggestions!

Chris
